name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  APP_NAME: "awesome-jason"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 
      
    - name: Push to Heroku
      run: git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ env.APP_NAME }}.git origin/master:master

#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    - name: Login to Heroku Container registry
#      env: 
#        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#      run: heroku container:login 
